---
name: "Meilisearch"
guid: "d9e8fe69-9e5a-4ae9-bfc2-590db8da69e1"
version: "0.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "A Meilisearch Plugin for Jellyfin"
imageUrl: https://raw.githubusercontent.com/meilisearch/meilisearch/refs/heads/main/assets/meilisearch-logo-dark.svg
description: >
  This is a plugin that try to use Meilisearch to speedup the search of jellyfin.
  Inspired by Jellysearch
category: "General"
owner: "a.sac."
artifacts:
  - "Jellyfin.Plugin.Meilisearch.dll"
  - "Jellyfin.Plugin.Meilisearch.pdb"
  - "Meilisearch.dll"
  - "Microsoft.IdentityModel.Abstractions.dll"
  - "Microsoft.IdentityModel.JsonWebTokens.dll"
  - "Microsoft.IdentityModel.Logging.dll"
  - "Microsoft.IdentityModel.Tokens.dll"
  - "System.IdentityModel.Tokens.Jwt.dll"
changelog: changelog
